#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

cmd = 'java -cp bin:lib/antlr-4.4-complete.jar wacc.Compiler'
if (ARGV.empty?) then
  puts `#{cmd}`
elsif (ARGV.length == 1) then
  puts `#{cmd} #{ARGV[0]}`
else
  puts `#{cmd} #{ARGV[0]} #{ARGV[1]}`
end

exit $?.exitstatus
