#!/usr/bin/ruby

def testFile(fileName, errCode)
  cmd = `./compile #{fileName}`
  code = $?.exitstatus
  if (code != errCode) then
   puts "#{fileName}: Expected: #{errCode} got #{code}"
   puts cmd
   puts "________________________________"
  end
end

def testDirectory(dirName, errCode)
  Dir.foreach(dirName) do |fileName|
    if (fileName == ".") || (fileName == "..") then
      next
    end
    fullName = "#{dirName}/#{fileName}"
    if (File.directory?(fullName)) then
      testDirectory(fullName, errCode)
    else
      testFile(fullName, errCode)
    end
  end
end

root = ARGV[0]
valid = "#{root}valid"
syntax = "#{root}invalid/syntaxErr"
semantic = "#{root}invalid/semanticErr"

puts "Valid Tests:"
testDirectory(valid, 0)
puts ""
puts ""
puts ""
puts ""
puts "Syntax Tests:"
testDirectory(syntax, 100)
puts ""
puts ""
puts ""
puts ""
puts "Semantic Tests:"
testDirectory(semantic, 200)
