#!/usr/bin/ruby

def getExitCode(fileName)
  foundExit = false
  File.foreach(fileName) do |line|
    if (foundExit) then
      return line.match('[0-9]+')[0].to_i
    end
    if (line.start_with?("\# Exit:")) then
      foundExit = true
    end
  end
end

def getOutput(fileName)
  output = ""
  foundOut = false
  File.foreach(fileName) do |line|
    if (foundOut) then
      if (!line.start_with?('#')) then
        return output
      else
        
      end
    end
    if (line.start_with?("\# Output:")) then
      foundExit = true
    end
  end
end

def compareOutput(expected, actual, input, output)
  if (expected == "\#empty\#") then
    return actual == ""
  end
  expected.gsub!('#input#', input)
  expected.gsub!('#output#', output)
  puts expected.split('#addrs#') == actual.split(/0x[0-9]+/)
end

puts getExitCode(ARGV[0])
